### ISSUE TITLE
checklist do report

### ISSUE THREAD

**Issue by philsf** [philsf-biostat/SAR-2021-012-JG#7]
- [x] Title
- [x] Objective
- [x] Context (from SAP)
- [x] Data & Methods (from SAP)
- [x] Conclusions match the results
- [x] Observations
- [x] remove watermark
- [x] update TOC
- [x] render private + public version
